create table "public"."files" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "original_name" text not null,
    "status" text not null default 'PROCESSING'
);

alter table "public"."files" enable row level security;


CREATE UNIQUE INDEX files_pkey ON public.files USING btree (id);


alter table "public"."files" add constraint "files_pkey" PRIMARY KEY using index "files_pkey";
